### ISSUE TITLE
Error searching books: Request failed with status code 403

### ISSUE THREAD

**Issue by mniittymaki** [Revisor01/abs-storytel-provider#8]
Im suddenly getting this error when trying to find metadata for my books : Error searching books: Request failed with status code 403

What can I do?

**Comment by strese** [comment]
I'm also seeing this

Edit:
If I restart the "abs-storytel-provider" container, I get a few searches that work and have results. But after 3-4 searches I get the "Request failed with status code 403" error in container logs and no results in audiobookshelf.
I've tried this on the same books also, that had results about ten minutes prior the next attempt that ends up not having any results.

**Comment by Revisor01** [comment]
This has been fixed. The root cause was rate-limiting by Storytel's API.

Each search was triggering 6 API calls (1 search + 5 individual book detail lookups via `getBookInfoForContent.action`). After a few searches, Storytel would respond with 403.

The fix: The search endpoint already returns all needed metadata (book, abook, ebook) directly in the response. The extra detail calls were unnecessary and have been removed. Now each search only makes **1 API call** instead of 6.

Please update your container to the latest image:
```bash
docker compose pull && docker compose up -d
```

**Comment by mniittymaki** [comment]
Thanks!

I re-installed the plugin, but still got the same error for some books even though I can find them on Storytel..

This audiobook is a great example: https://www.storytel.com/fi/books/tulevaisuus-mihin-ven%C3%A4j%C3%A4-oikein-on-matkalla-12268077

<img width="816" height="523" alt="Image" src="https://github.com/user-attachments/assets/3043d5cd-1d43-4469-b9c9-8084b49d1f31" />

<img width="468" height="119" alt="Image" src="https://github.com/user-attachments/assets/c14b5198-3a83-4d7c-83c2-39e327207e2a" />

**Comment by sae34ko1** [comment]
I also have the same issue. Even after a update or complete re-install of the plugin it still searches 5-6 times and returns the same errror as posted above. First search works then nothing.

**Comment by strese** [comment]
I've updated the container to latest image, but still have the same issue.
